from . import localiza_gps_asignacion
from . import localiza_asignado
from . import localiza_activo_cinta
from . import localiza_telefonia_compania
from . import localiza_activo_desmonte
from . import localiza_activo_equipo_instalar
from . import localiza_activo
from . import localiza_telefonia_linea
from . import localiza_activo_linea
from . import localiza_catalogo_marca
from . import localiza_activo_modelo
from . import localiza_equipo_modelo
from . import localiza_telefonia_plan_datos
from . import localiza_telefonia_registro_linea
from . import localiza_equipo_registro
from . import localiza_telefonia_sim
from . import localiza_activo_senuelo
from . import localiza_activo_tipo_cinta
from . import localiza_servicio_tipo
from . import localiza_activo_cinta_tag
from . import localiza_equipo_registro_stage
from . import localiza_activo_line
from . import localiza_equipo_marca
from . import localiza_telefonia_registro_linea_detalle
from . import extension_product_product
from . import extension_product_template
